version: 2
jobs:
  build:
    working_directory: ~/python-ci
    docker:
      - image: circleci/python:3.7.1  # primary container for the build job
    steps:
      - checkout # check out source code to working directory
      - run:
        command: |
          python test/math-test.py test
